<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs" version="2.0">

  <!-- MARC - RDA Carrier Map -->
  <xsl:variable name="marcCarrierMap">
    <carrier rdaType="aperture card">aperture card</carrier>
    <carrier rdaType="audio cartridge">audio cartridge</carrier>
    <carrier rdaType="audio cartridge">sound cartridge</carrier>
    <carrier rdaType="audio cylinder">audio cylinder</carrier>
    <carrier rdaType="audio cylinder">cylinder</carrier>
    <carrier rdaType="audio disc">audio disc</carrier>
    <carrier rdaType="audio disc">sound disc</carrier>
    <carrier rdaType="audio roll">audio roll</carrier>
    <carrier rdaType="audiocassette">audiocassette</carrier>
    <carrier rdaType="audiocassette">sound cassette</carrier>
    <carrier rdaType="audiotape reel">audiotape reel</carrier>
    <carrier rdaType="card">activity card</carrier>
    <carrier rdaType="card">card</carrier>
    <carrier rdaType="card">flash card</carrier>
    <carrier rdaType="card">postcard</carrier>    
    <carrier rdaType="computer card">computer card</carrier>
    <carrier rdaType="computer chip cartridge">computer chip cartridge</carrier>
    <carrier rdaType="computer disc cartridge">computer disc cartridge</carrier>
    <carrier rdaType="computer disc">computer disc</carrier>
    <carrier rdaType="computer disc">magnetic disk</carrier>
    <carrier rdaType="computer disc">magneto-optical disc</carrier>
    <carrier rdaType="computer disc">optical disc</carrier>
    <carrier rdaType="computer tape cartridge">computer tape cartridge</carrier>
    <carrier rdaType="computer tape cartridge">tape cartridge</carrier>
    <carrier rdaType="computer tape cassette">computer tape cassette</carrier>
    <carrier rdaType="computer tape cassette">tape cassette</carrier>
    <carrier rdaType="computer tape reel">computer tape reel</carrier>
    <carrier rdaType="computer tape reel">tape reel</carrier>
    <carrier rdaType="film cartridge">film cartridge</carrier>
    <carrier rdaType="film cassette">film cassette</carrier>
    <carrier rdaType="film reel">film reel</carrier>
    <carrier rdaType="film roll">film roll</carrier>
    <carrier rdaType="filmslip">filmslip</carrier>
    <carrier rdaType="filmstrip cartridge">filmstrip cartridge</carrier>
    <carrier rdaType="filmstrip">filmstrip</carrier>
    <carrier rdaType="filmstrip">other filmstrip type</carrier>
    <carrier rdaType="flipchart">flipchart</carrier>
    <carrier rdaType="microfiche cassette">microfiche cassette</carrier>
    <carrier rdaType="microfiche">microfiche</carrier>
    <carrier rdaType="microfilm cartridge">microfilm cartridge</carrier>
    <carrier rdaType="microfilm cassette">microfilm cassette</carrier>
    <carrier rdaType="microfilm reel">microfilm reel</carrier>
    <carrier rdaType="microfilm roll">microfilm roll</carrier>
    <carrier rdaType="microfilm slip">microfilm slip</carrier>
    <carrier rdaType="microopaque">microopaque</carrier>
    <carrier rdaType="microscope slide">microscope slide</carrier>
    <carrier rdaType="object">celestial globe</carrier>
    <carrier rdaType="object">diorama</carrier>
    <carrier rdaType="object">earth moon globe</carrier>
    <carrier rdaType="object">globe</carrier>
    <carrier rdaType="object">model</carrier>
    <carrier rdaType="object">object</carrier>
    <carrier rdaType="object">planetary or lunar globe</carrier>
    <carrier rdaType="object">realia</carrier>
    <carrier rdaType="object">terrestrial globe</carrier>
    <carrier rdaType="online resource">online resource</carrier>
    <carrier rdaType="other audio carrier">other audio carrier</carrier>
    <carrier rdaType="other audio carrier">sound recording</carrier>
    <carrier rdaType="other computer carrier">electronic</carrier>
    <carrier rdaType="other computer carrier">electronic resource</carrier>
    <carrier rdaType="other computer carrier">other computer carrier</carrier>
    <carrier rdaType="other microform carrier">other microform carrier</carrier>
    <carrier rdaType="other microscopic carrier">other microscopic carrier</carrier>
    <carrier rdaType="other projected carrier">motion picture</carrier>
    <carrier rdaType="other projected carrier">other projected carrier</carrier>
    <carrier rdaType="other stereographic carrier">other stereographic carrier</carrier>
    <carrier rdaType="other unmediated carrier">art original</carrier>
    <carrier rdaType="other unmediated carrier">art reproduction</carrier>
    <carrier rdaType="other unmediated carrier">braille</carrier>
    <carrier rdaType="other unmediated carrier">chart</carrier>
    <carrier rdaType="other unmediated carrier">collage</carrier>
    <carrier rdaType="other unmediated carrier">diagram</carrier>
    <carrier rdaType="other unmediated carrier">drawing</carrier>
    <carrier rdaType="other unmediated carrier">game</carrier>
    <carrier rdaType="other unmediated carrier">graphic</carrier>
    <carrier rdaType="other unmediated carrier">icon</carrier>
    <carrier rdaType="other unmediated carrier">large print</carrier>
    <carrier rdaType="other unmediated carrier">map</carrier>
    <carrier rdaType="other unmediated carrier">moon</carrier>
    <carrier rdaType="other unmediated carrier">non-projected graphic</carrier>
    <carrier rdaType="other unmediated carrier">nonprojected graphic</carrier>
    <carrier rdaType="other unmediated carrier">other unmediated carrier</carrier>
    <carrier rdaType="other unmediated carrier">painting</carrier>
    <carrier rdaType="other unmediated carrier">photograph</carrier>
    <carrier rdaType="other unmediated carrier">photomechanical print</carrier>
    <carrier rdaType="other unmediated carrier">photonegative</carrier>
    <carrier rdaType="other unmediated carrier">photoprint</carrier>
    <carrier rdaType="other unmediated carrier">picture</carrier>
    <carrier rdaType="other unmediated carrier">print</carrier>
    <carrier rdaType="other unmediated carrier">profile</carrier>
    <carrier rdaType="other unmediated carrier">regular print</carrier>
    <carrier rdaType="other unmediated carrier">remote-sensing image</carrier>
    <carrier rdaType="other unmediated carrier">section</carrier>
    <carrier rdaType="other unmediated carrier">study print</carrier>
    <carrier rdaType="other unmediated carrier">tactile, with no writing system</carrier>
    <carrier rdaType="other unmediated carrier">technical drawing</carrier>
    <carrier rdaType="other unmediated carrier">text in looseleaf binder</carrier>
    <carrier rdaType="other unmediated carrier">toy</carrier>
    <carrier rdaType="other unmediated carrier">view</carrier>
    <carrier rdaType="other video carrier">other video carrier</carrier>
    <carrier rdaType="overhead transparency">overhead transparency</carrier>
    <carrier rdaType="overhead transparency">transparency</carrier>
    <carrier rdaType="online resource">remote</carrier>
    <!--<carrier rdaType="remote">remote</carrier>-->
    <carrier rdaType="roll">roll</carrier>
    <carrier rdaType="sheet">radiograph</carrier>
    <carrier rdaType="sheet">sheet</carrier>
    <carrier rdaType="slide">slide</carrier>
    <carrier rdaType="sound track reel">sound track reel</carrier>
    <carrier rdaType="sound track reel">sound-tape reel</carrier>
    <carrier rdaType="sound track reel">sound-track film</carrier>
    <carrier rdaType="stereograph card">stereograph card</carrier>
    <carrier rdaType="stereograph disc">stereograph disc</carrier>
    <carrier rdaType="unspecified">kit</carrier>
    <carrier rdaType="unspecified">microform</carrier>
    <carrier rdaType="unspecified">unspecified</carrier>
    <carrier rdaType="unspecified">videorecording</carrier>
    <carrier rdaType="video cartridge">video cartridge</carrier>
    <carrier rdaType="video cartridge">videocartridge</carrier>
    <carrier rdaType="videocassette">videocassette</carrier>
    <carrier rdaType="videodisc">videodisc</carrier>
    <carrier rdaType="videotape reel">videoreel</carrier>
    <carrier rdaType="videotape reel">videotape reel</carrier>
    <carrier rdaType="volume">atlas</carrier>
    <carrier rdaType="volume">volume</carrier>
    <carrier rdaType="wire recording">wire recording</carrier>
  </xsl:variable>

</xsl:stylesheet>
