<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs" version="2.0">

  <!-- MODS typeOfResource - RDA media and carrier Map -->
  <xsl:variable name="resourceMap">
    <content resourceType="cartographic">atlas</content>
    <content resourceType="cartographic">cartographic dataset</content>
    <content resourceType="cartographic">cartographic image</content>
    <content resourceType="cartographic">cartographic moving image</content>
    <content resourceType="cartographic">cartographic tactile image</content>
    <content resourceType="cartographic">cartographic tactile three-dimensional form</content>
    <content resourceType="cartographic">cartographic three-dimensional form</content>
    <content resourceType="cartographic">cartographic</content>
    <content resourceType="cartographic">celestial globe</content>
    <content resourceType="cartographic">earth moon globe</content>
    <content resourceType="cartographic">globe</content>
    <content resourceType="cartographic">map</content>
    <content resourceType="cartographic">planetary or lunar globe</content>
    <content resourceType="cartographic">terrestrial globe</content>
    <content resourceType="mixed material">mixed material</content>
    <content resourceType="moving image">film cartridge</content>
    <content resourceType="moving image">film cassette</content>
    <content resourceType="moving image">film reel</content>
    <content resourceType="moving image">film roll</content>
    <content resourceType="moving image">filmslip</content>
    <content resourceType="moving image">filmstrip cartridge</content>
    <content resourceType="moving image">filmstrip</content>
    <content resourceType="moving image">motion picture</content>
    <content resourceType="moving image">moving image</content>
    <content resourceType="moving image">other video carrier</content>
    <content resourceType="moving image">three-dimensional moving image</content>
    <content resourceType="moving image">two-dimensional moving image</content>
    <content resourceType="moving image">video cartridge</content>
    <content resourceType="moving image">video</content>
    <content resourceType="moving image">videocartridge</content>
    <content resourceType="moving image">videocassette</content>
    <content resourceType="moving image">videodisc</content>
    <content resourceType="moving image">videorecording</content>
    <content resourceType="moving image">videoreel</content>
    <content resourceType="moving image">videotape reel</content>
    <content resourceType="notated music">notated music</content>
    <content resourceType="notated music">tactile notated music</content>
    <content resourceType="software, multimedia">computer card</content>
    <content resourceType="software, multimedia">computer chip cartridge</content>
    <content resourceType="software, multimedia">computer dataset</content>
    <content resourceType="software, multimedia">computer disc cartridge</content>
    <content resourceType="software, multimedia">computer disc</content>
    <content resourceType="software, multimedia">computer program</content>
    <content resourceType="software, multimedia">computer tape cartridge</content>
    <content resourceType="software, multimedia">computer tape cassette</content>
    <content resourceType="software, multimedia">computer tape reel</content>
    <content resourceType="software, multimedia">computer</content>
    <content resourceType="software, multimedia">electronic resource</content>
    <content resourceType="software, multimedia">electronic</content>
    <content resourceType="software, multimedia">magnetic disk</content>
    <content resourceType="software, multimedia">magneto-optical disc</content>
    <content resourceType="software, multimedia">online resource</content>
    <content resourceType="software, multimedia">optical disc</content>
    <content resourceType="software, multimedia">other computer carrier</content>
    <content resourceType="software, multimedia">remote</content>
    <content resourceType="software, multimedia">software, multimedia</content>
    <content resourceType="software, multimedia">tape cartridge</content>
    <content resourceType="software, multimedia">tape cassette</content>
    <content resourceType="software, multimedia">tape reel</content>
    <content resourceType="sound recording">audio cartridge</content>
    <content resourceType="sound recording">audio cylinder</content>
    <content resourceType="sound recording">audio disc</content>
    <content resourceType="sound recording">audio roll</content>
    <content resourceType="sound recording">audio</content>
    <content resourceType="sound recording">audiocassette</content>
    <content resourceType="sound recording">audiotape reel</content>
    <content resourceType="sound recording">cylinder</content>
    <content resourceType="sound recording">other audio carrier</content>
    <content resourceType="sound recording">sound cartridge</content>
    <content resourceType="sound recording">sound cassette</content>
    <content resourceType="sound recording">sound disc</content>
    <content resourceType="sound recording">sound recording</content>
    <content resourceType="sound recording">sound track reel</content>
    <content resourceType="sound recording">sound-tape reel</content>
    <content resourceType="sound recording">sound-track film</content>
    <content resourceType="sound recording">wire recording</content>
    <content resourceType="sound recording-musical">performed music</content>
    <content resourceType="sound recording-musical">sound recording-musical</content>
    <content resourceType="sound recording-nonmusical">sound recording-nonmusical</content>
    <content resourceType="sound recording-nonmusical">sounds</content>
    <content resourceType="sound recording-nonmusical">spoken word</content>
    <content resourceType="still image">chart</content>
    <content resourceType="still image">collage</content>
    <content resourceType="still image">diagram</content>
    <content resourceType="still image">drawing</content>
    <content resourceType="still image">microscope slide</content>
    <content resourceType="still image">non-projected graphic</content>
    <content resourceType="still image">nonprojected graphic</content>
    <content resourceType="still image">other microscopic carrier</content>
    <content resourceType="still image">overhead transparency</content>
    <content resourceType="still image">photomechanical print</content>
    <content resourceType="still image">photonegative</content>
    <content resourceType="still image">photoprint</content>
    <content resourceType="still image">picture</content>
    <content resourceType="still image">profile</content>
    <content resourceType="still image">remote sensing image</content>
    <content resourceType="still image">slide</content>
    <content resourceType="still image">stereograph card</content>
    <content resourceType="still image">stereograph disc</content>
    <content resourceType="still image">stereographic</content>
    <content resourceType="still image">still image</content>
    <content resourceType="still image">tactile image</content>
    <content resourceType="still image">technical drawing</content>
    <content resourceType="still image">transparency</content>
    <content resourceType="still image">view</content>
    <content resourceType="text">large print</content>
    <content resourceType="text">notated movement</content>
    <content resourceType="text">print</content>
    <content resourceType="text">regular print</content>
    <content resourceType="text">tactile notated movement</content>
    <content resourceType="text">tactile text</content>
    <content resourceType="text">text in looseleaf binder</content>
    <content resourceType="text">text</content>
    <content resourceType="three dimensional object">art original</content>
    <content resourceType="three dimensional object">diorama</content>
    <content resourceType="three dimensional object">flipchart</content>
    <content resourceType="three dimensional object">game</content>
    <content resourceType="three dimensional object">model</content>
    <content resourceType="three dimensional object">object</content>
    <content resourceType="three dimensional object">painting</content>
    <content resourceType="three dimensional object">realia</content>
    <content resourceType="three dimensional object">tactile three-dimensional form</content>
    <content resourceType="three dimensional object">three dimensional object</content>
    <content resourceType="three dimensional object">three-dimensional object</content>
    <content resourceType="three dimensional object">three dimensional form</content>
    <content resourceType="three dimensional object">three-dimensional form</content>
    <content resourceType="three dimensional object">toy</content>
    <content resourceType="unspecified">aperture card</content>
    <content resourceType="unspecified">art reproduction</content>
    <content resourceType="unspecified">braille</content>
    <content resourceType="unspecified">card</content>
    <content resourceType="unspecified">flash card</content>
    <content resourceType="unspecified">graphic</content>
    <content resourceType="unspecified">kit</content>
    <content resourceType="unspecified">microfiche cassette</content>
    <content resourceType="unspecified">microfiche</content>
    <content resourceType="unspecified">microfilm cartridge</content>
    <content resourceType="unspecified">microfilm cassette</content>
    <content resourceType="unspecified">microfilm reel</content>
    <content resourceType="unspecified">microfilm roll</content>
    <content resourceType="unspecified">microfilm slip</content>
    <content resourceType="unspecified">microfilm</content>
    <content resourceType="unspecified">microform</content>
    <content resourceType="unspecified">microopaque</content>
    <content resourceType="unspecified">moon</content>
    <content resourceType="unspecified">other microform carrier</content>
    <content resourceType="unspecified">other projected carrier</content>
    <content resourceType="unspecified">other stereographic carrier</content>
    <content resourceType="unspecified">other unmediated carrier</content>
    <content resourceType="unspecified">projected graphic</content>
    <content resourceType="unspecified">projected</content>
    <content resourceType="unspecified">roll</content>
    <content resourceType="unspecified">sheet</content>
    <content resourceType="unspecified">tactile material</content>
    <content resourceType="unspecified">tactile, with no writing system</content>
    <content resourceType="unspecified">unspecified</content>
    <content resourceType="unspecified">volume</content>
  </xsl:variable>
</xsl:stylesheet>
