<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs" version="2.0">

  <!-- MARC Code List for Standrd Identifier Source, https://www.loc.gov/standards/sourcelist/standard-identifier.html, retrieved 2020/09/25 -->
  <xsl:variable name="StandardIdentifierSourceCodes">
    <code>agorha</code>
    <code>agrovoc</code>
    <code>allmovie</code>
    <code>allmusic</code>
    <code>allocine</code>
    <code>amnbo</code>
    <code>ansi</code>
    <code>artsy</code>
    <code>artukart</code>
    <code>artukaw</code>
    <code>atg</code>
    <code>balat</code>
    <code>bbcth</code>
    <code>bdusc</code>
    <code>belvku</code>
    <code>belvwrk</code>
    <code>benezit</code>
    <code>bfi</code>
    <code>bibbi</code>
    <code>bigenc</code>
    <code>bnfcg</code>
    <code>bpn</code>
    <code>bsi</code>
    <code>cabt</code>
    <code>cana</code>
    <code>cantic</code>
    <code>cbwpid</code>
    <code>cerl</code>
    <code>cgndb</code>
    <code>clara</code>
    <code>cnbksy</code>
    <code>csfdcz</code>
    <code>danacode</code>
    <code>darome</code>
    <code>datoses</code>
    <code>discogs</code>
    <code>dkfilm</code>
    <code>doi</code>
    <code>dpb</code>
    <code>ean</code>
    <code>eidr</code>
    <code>emlo</code>
    <code>fast</code>
    <code>fidecp</code>
    <code>filmaff</code>
    <code>filmport</code>
    <code>findagr</code>
    <code>fisa</code>
    <code>freebase</code>
    <code>gacsch</code>
    <code>gec</code>
    <code>geogndb</code>
    <code>geonames</code>
    <code>gettyaat</code>
    <code>gettyart</code>
    <code>gettyobj</code>
    <code>gettytgn</code>
    <code>gettyulan</code>
    <code>gnd</code>
    <code>gnis</code>
    <code>goodra</code>
    <code>gtaa</code>
    <code>gtin-14</code>
    <code>hdl</code>
    <code>iaafa</code>
    <code>ibdb</code>
    <code>iconauth</code>
    <code>idref</code>
    <code>imdb</code>
    <code>isan</code>
    <code>isbn-a</code>
    <code>isbnre</code>
    <code>isbnsbn</code>
    <code>isni</code>
    <code>iso</code>
    <code>isfdbau</code>
    <code>isfdbaw</code>
    <code>isfdbma</code>
    <code>isfdbpu</code>
    <code>isil</code>
    <code>issn-l</code>
    <code>issue-number</code>
    <code>istc</code>
    <code>iswc</code>
    <code>itar</code>
    <code>kda</code>
    <code>kdw</code>
    <code>kinopo</code>
    <code>lattes</code>
    <code>lcmd</code>
    <code>lei</code>
    <code>libaus</code>
    <code>margaz</code>
    <code>matrix-number</code>
    <code>mesh</code>
    <code>mocofo</code>
    <code>moma</code>
    <code>morana</code>
    <code>moviemetf</code>
    <code>moviemetr</code>
    <code>munzing</code>
    <code>muscl</code>
    <code>musicb</code>
    <code>nacat</code>
    <code>natgazfid</code>
    <code>nga</code>
    <code>ngva</code>
    <code>ngvw</code>
    <code>nipo</code>
    <code>nndb</code>
    <code>npg</code>
    <code>odnb</code>
    <code>ofdb</code>
    <code>onix</code>
    <code>opensm</code>
    <code>orcid</code>
    <code>oxforddnb</code>
    <code>permid</code>
    <code>picnypl</code>
    <code>pleiades</code>
    <code>pnta</code>
    <code>porthu</code>
    <code>prabook</code>
    <code>rbmsbt</code>
    <code>rbmsgt</code>
    <code>rbmspe</code>
    <code>rbmsppe</code>
    <code>rbmspt</code>
    <code>rbmsrd</code>
    <code>rbmste</code>
    <code>rid</code>
    <code>rkda</code>
    <code>saam</code>
    <code>scholaru</code>
    <code>scope</code>
    <code>scopus</code>
    <code>snac</code>
    <code>spotify</code>
    <code>sprfbsb</code>
    <code>sprfbsk</code>
    <code>sprfcbb</code>
    <code>sprfcfb</code>
    <code>sprfhoc</code>
    <code>sprfoly</code>
    <code>sprfpfb</code>
    <code>stw</code>
    <code>svfilm</code>
    <code>tatearid</code>
    <code>theatr</code>
    <code>trove</code>
    <code>unescot</code>
    <code>uri</code>
    <code>urn</code>
    <code>vd16</code>
    <code>vd17</code>
    <code>vd18</code>
    <code>vgmdb</code>
    <code>viaf</code>
    <code>videorecording-identifier</code>
    <code>wikidata</code>
    <code>wndla</code>
    <code>ysopai</code>
    <code>xgamea</code>
  </xsl:variable>

</xsl:stylesheet>
